# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from TinkoffPy.grpc import marketdata_pb2 as TinkoffPy_dot_grpc_dot_marketdata__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in TinkoffPy/grpc/marketdata_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketDataServiceStub(object):
    """Сервис для получения биржевой информации:<br/> 1. Свечи.<br/> 2. Стаканы.<br/> 3. Торговые статусы.<br/> 4. Лента сделок.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCandles = channel.unary_unary(
                '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetCandles',
                request_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetCandlesRequest.SerializeToString,
                response_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetCandlesResponse.FromString,
                _registered_method=True)
        self.GetLastPrices = channel.unary_unary(
                '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetLastPrices',
                request_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetLastPricesRequest.SerializeToString,
                response_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetLastPricesResponse.FromString,
                _registered_method=True)
        self.GetOrderBook = channel.unary_unary(
                '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetOrderBook',
                request_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetOrderBookRequest.SerializeToString,
                response_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetOrderBookResponse.FromString,
                _registered_method=True)
        self.GetTradingStatus = channel.unary_unary(
                '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetTradingStatus',
                request_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTradingStatusRequest.SerializeToString,
                response_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTradingStatusResponse.FromString,
                _registered_method=True)
        self.GetTradingStatuses = channel.unary_unary(
                '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetTradingStatuses',
                request_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTradingStatusesRequest.SerializeToString,
                response_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTradingStatusesResponse.FromString,
                _registered_method=True)
        self.GetLastTrades = channel.unary_unary(
                '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetLastTrades',
                request_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetLastTradesRequest.SerializeToString,
                response_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetLastTradesResponse.FromString,
                _registered_method=True)
        self.GetClosePrices = channel.unary_unary(
                '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetClosePrices',
                request_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetClosePricesRequest.SerializeToString,
                response_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetClosePricesResponse.FromString,
                _registered_method=True)
        self.GetTechAnalysis = channel.unary_unary(
                '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetTechAnalysis',
                request_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTechAnalysisRequest.SerializeToString,
                response_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTechAnalysisResponse.FromString,
                _registered_method=True)


class MarketDataServiceServicer(object):
    """Сервис для получения биржевой информации:<br/> 1. Свечи.<br/> 2. Стаканы.<br/> 3. Торговые статусы.<br/> 4. Лента сделок.
    """

    def GetCandles(self, request, context):
        """Запросить исторические свечи по инструменту.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLastPrices(self, request, context):
        """Запросить цены последних сделок по инструментам.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderBook(self, request, context):
        """Получить стакан по инструменту.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTradingStatus(self, request, context):
        """Запросить статус торгов по инструментам.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTradingStatuses(self, request, context):
        """Запросить статус торгов по инструментам.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLastTrades(self, request, context):
        """Запросить обезличенные сделки за последний час.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClosePrices(self, request, context):
        """Запросить цены закрытия торговой сессии по инструментам.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTechAnalysis(self, request, context):
        """Получить технические индикаторы по инструменту.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCandles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCandles,
                    request_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetCandlesRequest.FromString,
                    response_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetCandlesResponse.SerializeToString,
            ),
            'GetLastPrices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastPrices,
                    request_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetLastPricesRequest.FromString,
                    response_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetLastPricesResponse.SerializeToString,
            ),
            'GetOrderBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderBook,
                    request_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetOrderBookRequest.FromString,
                    response_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetOrderBookResponse.SerializeToString,
            ),
            'GetTradingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTradingStatus,
                    request_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTradingStatusRequest.FromString,
                    response_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTradingStatusResponse.SerializeToString,
            ),
            'GetTradingStatuses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTradingStatuses,
                    request_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTradingStatusesRequest.FromString,
                    response_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTradingStatusesResponse.SerializeToString,
            ),
            'GetLastTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastTrades,
                    request_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetLastTradesRequest.FromString,
                    response_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetLastTradesResponse.SerializeToString,
            ),
            'GetClosePrices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClosePrices,
                    request_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetClosePricesRequest.FromString,
                    response_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetClosePricesResponse.SerializeToString,
            ),
            'GetTechAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTechAnalysis,
                    request_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTechAnalysisRequest.FromString,
                    response_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTechAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tinkoff.public.invest.api.contract.v1.MarketDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tinkoff.public.invest.api.contract.v1.MarketDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketDataService(object):
    """Сервис для получения биржевой информации:<br/> 1. Свечи.<br/> 2. Стаканы.<br/> 3. Торговые статусы.<br/> 4. Лента сделок.
    """

    @staticmethod
    def GetCandles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetCandles',
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetCandlesRequest.SerializeToString,
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetCandlesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLastPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetLastPrices',
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetLastPricesRequest.SerializeToString,
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetLastPricesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetOrderBook',
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetOrderBookRequest.SerializeToString,
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetOrderBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTradingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetTradingStatus',
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTradingStatusRequest.SerializeToString,
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTradingStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTradingStatuses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetTradingStatuses',
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTradingStatusesRequest.SerializeToString,
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTradingStatusesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLastTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetLastTrades',
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetLastTradesRequest.SerializeToString,
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetLastTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClosePrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetClosePrices',
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetClosePricesRequest.SerializeToString,
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetClosePricesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTechAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetTechAnalysis',
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTechAnalysisRequest.SerializeToString,
            TinkoffPy_dot_grpc_dot_marketdata__pb2.GetTechAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MarketDataStreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MarketDataStream = channel.stream_stream(
                '/tinkoff.public.invest.api.contract.v1.MarketDataStreamService/MarketDataStream',
                request_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.MarketDataRequest.SerializeToString,
                response_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.MarketDataResponse.FromString,
                _registered_method=True)
        self.MarketDataServerSideStream = channel.unary_stream(
                '/tinkoff.public.invest.api.contract.v1.MarketDataStreamService/MarketDataServerSideStream',
                request_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.MarketDataServerSideStreamRequest.SerializeToString,
                response_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.MarketDataResponse.FromString,
                _registered_method=True)


class MarketDataStreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MarketDataStream(self, request_iterator, context):
        """Bidirectional-стрим предоставления биржевой информации.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarketDataServerSideStream(self, request, context):
        """Server-side стрим предоставления биржевой информации.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MarketDataStream': grpc.stream_stream_rpc_method_handler(
                    servicer.MarketDataStream,
                    request_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.MarketDataRequest.FromString,
                    response_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.MarketDataResponse.SerializeToString,
            ),
            'MarketDataServerSideStream': grpc.unary_stream_rpc_method_handler(
                    servicer.MarketDataServerSideStream,
                    request_deserializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.MarketDataServerSideStreamRequest.FromString,
                    response_serializer=TinkoffPy_dot_grpc_dot_marketdata__pb2.MarketDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tinkoff.public.invest.api.contract.v1.MarketDataStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tinkoff.public.invest.api.contract.v1.MarketDataStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketDataStreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MarketDataStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tinkoff.public.invest.api.contract.v1.MarketDataStreamService/MarketDataStream',
            TinkoffPy_dot_grpc_dot_marketdata__pb2.MarketDataRequest.SerializeToString,
            TinkoffPy_dot_grpc_dot_marketdata__pb2.MarketDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarketDataServerSideStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tinkoff.public.invest.api.contract.v1.MarketDataStreamService/MarketDataServerSideStream',
            TinkoffPy_dot_grpc_dot_marketdata__pb2.MarketDataServerSideStreamRequest.SerializeToString,
            TinkoffPy_dot_grpc_dot_marketdata__pb2.MarketDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
